[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/choosepart"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/garageindex"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/profile"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/anypartmanagement"
  to = "/index.html"
  status = 200
